@startuml caso_de_uso_candidato
!theme cerulean
left to right direction

actor Candidato

rectangle "Plataforma de Emprego" {
    usecase "Manter Perfil Pessoal" as UC_ManageProfile
  
    usecase "Buscar Vagas" as UC_SearchVacancies
    usecase "Manter Candidaturas" as UC_ManageApplications
 

}

Candidato --> UC_ManageProfile
Candidato --> UC_SearchVacancies
Candidato --> UC_ManageApplications

@enduml
