@startuml caso_de_uso_empresa
!theme cerulean
left to right direction

actor Empresa

rectangle "Plataforma de Emprego" {
  
    usecase "Manter Perfil" as UC_ManageProfile
    usecase "Manter Vagas" as UC_ManageVacancies
    usecase "Manter Candidaturas das Vagas" as UC_ManageApplications
   
}

Empresa --> UC_ManageProfile
Empresa --> UC_ManageVacancies
Empresa --> UC_ManageApplications

@enduml
