@startuml caso_de_uso_administrador
!theme cerulean
left to right direction

actor Administrador

rectangle "Plataforma de Emprego" {
    usecase "Manter Usuários" as UC_ManageCandidates
    usecase "Manter perfil de Empresas" as UC_ManageCompanies
    usecase "Manter Vagas" as UC_ManageVacancies
    usecase "Manter Candidaturas" as UC_ManageApplications

}

Administrador --> UC_ManageCandidates
Administrador --> UC_ManageCompanies
Administrador --> UC_ManageVacancies
Administrador --> UC_ManageApplications



@enduml
