@startuml caso_de_uso_visitante
!theme cerulean
left to right direction

actor Visitante

rectangle "Plataforma de Emprego" {
    usecase "Visualizar Vagas em Aberto" as UC_ViewVacancies

    usecase "Realizar Cadastro como Candidato" as UC_RegisterCandidate
    usecase "Realizar Cadastro como Empresa" as UC_RegisterCompany
   
}

Visitante --> UC_ViewVacancies
Visitante --> UC_RegisterCandidate
Visitante --> UC_RegisterCompany


@enduml
